# Builds a zip archive of a relase that can be downloaded and installed in a WordPress test environment.
# Files and folders that should be excluded from the build are specified in the .distignore file in the root folder.
name: Build release zip
on:
  push:
    branches:
      - beta
jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate zip
        uses: 10up/action-wordpress-plugin-build-zip@stable
